# --------------------------------------------------------------------------------------------- #
# Project name:          Sakila Business Mini-Capstone
# Author:                Sharleen Guerrero
# Date:                  April 24, 2026
# Project Objective:     The objective of this project is to conduct a comprehensive business 
#                        analysis of the Sakila  database by extracting and analyzing transactional
#                        data, identifying key performance trends, generating insights using SQL 
#                        queries, and providing data-driven recommendations. 
# ---------------------------------------------------------------------------------------------- #

USE sakila;

# Part 1 & 2: Business Analysis Questions & Query Development Logic

-- =========================================================
-- Question 1: 
-- Determine the total rental revenue generated by each store, 
-- including the earliest and latest payment dates. 
-- ==========================================================
SELECT s.store_id,
	SUM(p.amount) AS 'Total Revenue',
    MIN(p.payment_date) AS 'Earliest Payment',
    MAX(p.payment_date) AS 'Latest Payment'
FROM payment p
INNER JOIN staff sf
	ON p.staff_id = sf.staff_id
INNER JOIN store s
	ON s.store_id = sf.store_id
GROUP BY s.store_id
ORDER BY `Total Revenue` DESC;

-- Explanation of logic:
-- Question demands calculations of payments per store, but payment has no direct link to store.
-- Staff acts as the bridge between payments and store through staff.staff.id
-- SUM calculates total revenue, and MIN and MAX capture the entire payment period.


-- =========================================================
-- Question 2: 
-- Analyze the month-by-monthy revenue breakdown for each
-- store.
-- ==========================================================
SELECT s.store_id,
    DATE_FORMAT(p.payment_date, '%Y-%m') AS `Revenue Month`,
    SUM(p.amount) AS `Monthly Revenue`
FROM payment p
INNER JOIN staff sf
    ON p.staff_id = sf.staff_id
INNER JOIN store s
    ON sf.store_id = s.store_id
GROUP BY s.store_id, `Revenue Month`
ORDER BY s.store_id, `Revenue Month`;

-- Explanation of logic:
-- Question demands monthly revenue for each store, but again, payment has no direct link to store.
-- Staff acts as the bridge between payments and store through staff_id
-- DATE_FORMAT formats the revenue by month and year, and SUM aggregates the total revenue for each store.

-- =========================================================
-- Question 3: 
-- Compare total rental revenue between stores and calculate
-- percentage contribution.
-- ==========================================================
SELECT   s.store_id,
         SUM(p.amount) AS 'Total Revenue' ,                         
         ROUND(SUM(p.amount) / (SELECT SUM(amount) FROM payment) * 100, 2) AS 'Percentage Contribution'
FROM     payment p
INNER JOIN staff sf
	ON sf.staff_id = p.staff_id
INNER JOIN store s
	ON s.store_id = sf.store_id
GROUP BY s.store_id
ORDER BY `Percentage Contribution` DESC;

-- Explanation of logic:
-- Question demands for a comparison of revenue between stores and percentage contribution for each store. 
-- Staff acts as the bridge between payments and store through staff_id
-- A subquery (SELECT SUM(amount) FROM payment) calculates the grand total revenue across stores. 
-- Each each store's SUM is divided by the grand total and multiplied by 100 to get its percentage share.


-- =========================================================
-- Question 4: 
-- Evaluate rentals per month and average payment per category. 
-- ==========================================================
SELECT c.name AS 'Category',
	DATE_FORMAT(r.rental_date, '%Y-%m') AS 'Rental Month',
    COUNT(r.rental_id) AS 'Total Rentals',
    ROUND(AVG(p.amount), 2) AS 'Average Payment'
FROM rental r
INNER JOIN payment p
	ON r.rental_id = p.rental_id
INNER JOIN inventory i
	ON r.inventory_id = i.inventory_id
INNER JOIN film_category fc
    ON i.film_id = fc.film_id
INNER JOIN category c
    ON fc.category_id = c.category_id
GROUP BY `Category`, `Rental Month`
ORDER BY `Average Payment` DESC;

-- Explanation of logic:
-- Question demands for number of rentals per month and average payment per category. 
-- There's no direct link from rental to category name. Starting from rental allows COUNT of rentals 
-- and links out in to payment through rental_id, and to inventory through inventory_id.
-- DATE_FORMAT formats the rental date by month and year, COUNT counts rentals for each group, 
-- and AVG(p.amount) calculates the average payments amount for each category.


-- =========================================================
-- Question 5: 
-- Rank stores by revenue, rentals, and customer spending.  
-- ==========================================================
SELECT s.store_id,
    SUM(p.amount)        AS 'Total Revenue',
    COUNT(r.rental_id)   AS 'Total Rentals',
    RANK() OVER (ORDER BY SUM(p.amount) DESC) AS 'Revenue Rank'
FROM rental r
INNER JOIN payment p 
	ON r.rental_id = p.rental_id
INNER JOIN staff sf	
	ON p.staff_id = sf.staff_id
INNER JOIN store s
	ON sf.store_id = s.store_id
GROUP BY s.store_id
ORDER BY `Revenue Rank`;

-- Explanation of logic:
-- Question demands ranking stores by revenue and rentals, but payment has no direct link to store.
-- Rental connects to payment through rental_id, and payment connects to store through staff_id.
-- SUM calculates total revenue, COUNT counts total rentals, and RANK() combined with DESC orders stores by highest revenue.


-- =========================================================
-- Question 6: 
-- Identify highest revenue-generating film categories.  
-- ==========================================================
SELECT c.name AS 'Category Name', 
	SUM(p.amount) AS 'Category Revenue'
FROM payment p
INNER JOIN rental r
	ON r.rental_id = p.rental_id
INNER JOIN inventory i
	ON r.inventory_id = i.inventory_id
INNER JOIN film_category fc
	ON i.film_id = fc.film_id
INNER JOIN category c
	ON fc.category_ID = c.category_id
GROUP BY `Category Name`
ORDER BY `Category Revenue` DESC;

-- Explanation of Logic:
-- Question demands revenue for each film category from highest to lowest.
-- There is no direct link from payment to category, but a path is created.
-- Payment links to rental through rental_id, rental links to inventory through
-- inventory_id, inventory links to film category through film_id and finally 
-- category is reached through shared category_id.
-- SUM(p.amount) calculates total revenue and group by collapses revenue into one
-- row per category.
-- Revenue is ordered in descending order to display the highest revenue category first.



-- =========================================================
-- Question 7: 
-- Determine top revenue-generating customers.  
-- ==========================================================
SELECT CONCAT(c.first_name, ' ', c.last_name) AS 'Customer Name',
    SUM(p.amount) AS 'Total Revenue',
    RANK() OVER (ORDER BY SUM(p.amount) DESC) AS 'Customer Rank'
FROM customer c
INNER JOIN payment p
    ON c.customer_id = p.customer_id
GROUP BY c.customer_id, `Customer Name`
ORDER BY `Customer Rank`;
-- Explanation of logic:
-- Question demands the top revenue-generating customers.
-- Payment and customer share a direct link through customer_id. 
-- SUM(p.amount) calculates total revenue per customer, and RANK() orders customers by highest spend.
-- GROUP BY collapses payments into one row per customer.

SELECT 
    s.store_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    SUM(p.amount) AS total_spent,
    COUNT(r.rental_id) AS rental_count,
    RANK() OVER (PARTITION BY s.store_id ORDER BY SUM(p.amount) DESC) AS customer_rank
FROM customer c
JOIN store s ON c.store_id = s.store_id
JOIN payment p ON c.customer_id = p.customer_id
JOIN rental r ON p.rental_id = r.rental_id
GROUP BY s.store_id, c.customer_id;

-- =========================================================
-- Question 8: 
-- Analyze monthly rental trends by category.  
-- ==========================================================

-- =========================================================
-- Question 9: 
-- Evaluate staff performance in rentals and revenue.
-- ==========================================================

-- =========================================================
-- Question 10: 
-- Provide strategic recommendations for revenue growth.  
-- ==========================================================